apiVersion: v1
kind: Service
metadata:
  name: hellokubernetes-service
spec:
  selector:
    app: hellokubernetes
  ports:
  - protocol: "TCP"
    port: 5003
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellokubernetes
spec:
  selector:
    matchLabels:
      app: hellokubernetes
  replicas: 4
  template:
    metadata:
      labels:
        app: hellokubernetes
    spec:
      containers:
      - name: hellokubernetes
        image: hellokubernetes:0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
